# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "Omni CAE Testing"
version = "1.0.0"
description = "Testing utilities for Omni CAE"
category = "Internal"
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
keywords = ["kit", "cae", "testing"]
readme  = "docs/README.md"

[[python.module]]  # Main python module this extension provides, it will be publicly available as "import omni.cae.testing"
name = "omni.cae.testing"
